include(jazrb_root + '/spec/lib/spec_helper.js');
include(jazrb_root + '/lib/dramatis.js');
include(jazrb_root + '/lib/dramatis/class.js');
include(jazrb_root + '/lib/dramatis/actor.js');
include(jazrb_root + '/lib/dramatis/actor/name.js');
include(jazrb_root + '/lib/dramatis/actor/type.js');
include(jazrb_root + '/lib/dramatis/director.js');
include(jazrb_root + '/lib/dramatis/runtime.js');
include(jazrb_root + '/lib/dramatis/runtime/reactor.js');
